
workflows:
  ios-workflow:
    name: Build iOS
    instance_type: mac_mini_m1
    environment:
      flutter: default
      xcode: latest
    scripts:
      - name: Baixar pacotes do Flutter
        script: flutter pub get
      - name: Compilar projeto iOS
        script: flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/*.app
